### ISSUE TITLE
TypeError: len() of a 0-d tensor

### ISSUE THREAD

**Issue by Jayashree-Pougajendy** [kuc2477/pytorch-deep-generative-replay#4]
Hi,
I am facing the foll. issue using the pytorch, torchvision, and PIL versions (because of compatibility requirement with cuda 10.1) as:
torch: 1.4.0
torchvision: 0.5.0
PIL: 5.2.0

Traceback (most recent call last):
  File "./main.py", line 186, in <module>
    cuda=cuda
  File "/home/js/DGR_pytorch/train.py", line 102, in train
    collate_fn=collate_fn,
  File "/home/js/DGR_pytorch/dgr.py", line 130, in train_with_replay
    collate_fn=collate_fn,
  File "/home/js/DGR_pytorch/dgr.py", line 205, in _train_batch_trainable_with_replay
    callback(trainable, progress, batch_index, result)
  File "/home/js/DGR_pytorch/train.py", line 157, in cb
    result['g_loss'], 'generator g loss', iteration, env=env
  File "/home/js/DGR_pytorch/visual.py", line 87, in visualize_scalar
    [name], name, iteration, env=env
  File "/home/js/DGR_pytorch/visual.py", line 92, in visualize_scalars
    assert len(scalars) == len(names)
  File "/home/js/anaconda3/envs/env_con/lib/python3.5/site-packages/torch/tensor.py", line 445, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor

Kindly suggest an alternative. Thank you.

**Comment by luoluo14** [comment]
I would like to ask whether the problem has been solved.
